name: Publish to Ansible Galaxy

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Collection
      run: |
        ansible-galaxy collection build .
      working-directory: ${{ github.workspace }}

    - name: Publish Collection
      env:
        ANSIBLE_GALAXY_API_TOKEN: ${{ secrets.ANSIBLE_GALAXY_API_TOKEN }}
      run: |
        ansible-galaxy collection publish --token $ANSIBLE_GALAXY_API_TOKEN *.tar.gz
      working-directory: ${{ github.workspace }}
